import type { Metadata } from "next";
import "./globals.css";

import { ClerkProvider, Show, SignInButton, SignOutButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { ToastProvider } from "@/hooks/useToast";

export const metadata: Metadata = {
  title: "AI N2N",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body >

        <ClerkProvider>
          <ToastProvider>
            {children}
          </ToastProvider>
        </ClerkProvider>

      </body>
    </html>
  );
}

